### PR TITLE
Update VM to latest

### PR DESCRIPTION
**Pull request by axic**
Made some of these updates back in December, just never got to fully finish them. This version seems to be working, updated to the very latest ethereumjs-vm.

### CODE REVIEW

**Comment by chriseth** [comment]
Thanks a lot! Unfortunately, I get "VM Exception: invalid JUMP" as soon as I use a library, like here:

```
library B {
    function f() returns (address)  { return msg.sender; }
}
contract A {
    function f() returns (address) { return  B.f(); }
}
```

Does it work for you?

**Comment by axic** [comment]
I didn't try it with libraries. It may even be an issue in the VM, it certainly requires a lot of testing as there were many changes in it.

Is it working with the old one?

**Comment by axic** [comment]
It doesn't seem to be working on the current one either, I get:
```
Result: "0x"
Cost: 206158408936 gas. 
```

Which equals to exception, except now it is displayed instead of maxGasUsed.

I think the problem lies in `deployLibrary`, which doesn't get back the address properly?

**Comment by axic** [comment]
Ahh, it is not set to homestead, thus `delegatecall` is not available.

`ethereumjs/common` needs an update too to have the proper homestead block number (cc @wanderer)

**Comment by axic** [comment]
This version should work with homestead.

@chriseth your example seems to work, but more testing would be welcome

**Comment by wanderer** [comment]
i think you should move the 'enableHomestead' option to the VM constructor there

**Comment by axic** [comment]
I've added the option to `runTx`, but I was going to change it to the global option.

**Pull request merged**
