### PR TITLE
Add multiple files and local imports

### PR DESCRIPTION
**Pull request by d11e9**
- add, rename, delete multitple local files
- allow imports for local files
- allow recusive imports `a` imports `b` imports `c` etc
- ~~[dont merge] show usage in example~~

Check it out here: http://d11e9.github.io/browser-solidity/ in ~~example solidty fails to import "test" until you add a file named "test"~~.

Updated to include changes proposed and contributed by @chriseth:
- backwards compatibility
- improved file storage scheme `localStorage[key]`
- focus editor on tab change

### CODE REVIEW

**Comment by chriseth** [comment]
Suggestion: Listen for `<return>` in the file renaming input box.

**Comment by d11e9** [comment]
Certainly

**Comment by d11e9** [comment]
Done. ok to merge.

**Comment by chriseth** [comment]
This is a really great pull request, but I think there are still some points that should still be addressed before this can be merged:
- the change should be backwards compatible, i.e. old content should be moved into the new format (already did that in my PR)
- I think that maintaining a list of files plus the contents of the files creates too much problems. Could we store all files under keys `sol-cache-file-FILENAME` and simply go through `window.localStorage` searching for that prefix?
- If files are switched, the editor loses focus.

I resolved the merge conflict and already added some commits in #23, but will not work on it further for now.

By the way, why don't you use `window.localStorage` as an object (`window.localStorage[newName] = window.localStorage[oldName]`)?

**Comment by d11e9** [comment]
Agree with all feedback and will address.

Re: editor loses focus, do you think cursor location should be preserved, or is that a nice to have?

**Pull request merged**
