### PR TITLE
Fix runTx constant call with args to real eth node

### PR DESCRIPTION
**Pull request by lastperson**
Arguments have been lost previously. The only way I've found is to remove signature from the data, then split it on 32 bytes chunks, add "0x" in front of each chunk, and `apply` it to the `func[method].call`.

### CODE REVIEW

**Comment by chriseth** [comment]
Thanks for taking care of this. The old code is obviously totally wrong. Can you try to get it to a point where we call `web3.eth.call`? You can probably even use the way the tx object is constructed for both alternatives.

**Comment by lastperson** [comment]
It's quite easy to do what you ask, but then the return value of `web3.eth.call` needs to be parsed. Working on it now.

**Comment by chriseth** [comment]
Yes, take a look at #127

**Comment by lastperson** [comment]
Apparently it is possible to do `contract.method.call(transaction)` but the implementation is broken in `web3`, so I will try to push changes there first.

**Comment by lastperson** [comment]
@chriseth I had a conversation with web3 guys, and they are planning to expose `decode` function that should be used in order to parse `web3.eth.call` results. So here is what I propose, we put a pure `web3.eth.call` in place of constant calls to get a correct (though encoded) output, and when `decode` will be exposed we'll add it here.

**Comment by chriseth** [comment]
Sounds good, thanks!

**Pull request merged**
